# Generated by Django 5.0.7 on 2024-09-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='station',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
